export const TAO_DONHANG_REQUEST = 'TAO_DONHANG_REQUEST';
export const TAO_DONHANG_THANHCONG = 'TAO_DONHANG_THANHCONG';
export const TAO_DONHANG_THATBAI = 'TAO_DONHANG_THATBAI';
export const TAYTRANG_DONHANG = 'TAYTRANG_DONHANG';

export const THANHTOAN_DONHANG_REQUEST = 'THANHTOAN_DONHANG_REQUEST';
export const THANHTOAN_DONHANG_THANHCONG = 'THANHTOAN_DONHANG_THANHCONG';
export const THANHTOAN_DONHANG_THATBAI = 'THANHTOAN_DONHANG_THATBAI';
export const TAYTRANG_THANHTOAN_DONHANG = 'TAYTRANG_THANHTOAN_DONHANG';

export const CHITIET_DONHANG_REQUEST = 'CHITIET_DONHANG_REQUEST'
export const CHITIET_DONHANG_THANHCONG = 'CHITIET_DONHANG_THANHCONG'
export const CHITIET_DONHANG_THATBAI = 'CHITIET_DONHANG_THATBAI'

export const DANHSACH_DONHANG_REQUEST = 'DANHSACH_DONHANG_REQUEST'
export const DANHSACH_DONHANG_THANHCONG = 'DANHSACH_DONHANG_THANHCONG'
export const DANHSACH_DONHANG_THATBAI = 'DANHSACH_DONHANG_THATBAI'

export const DANHSACH_DONHANG_ADMIN_REQUEST = 'DANHSACH_DONHANG_ADMIN_REQUEST'
export const DANHSACH_DONHANG_ADMIN_THANHCONG = 'DANHSACH_DONHANG_ADMIN_THANHCONG'
export const DANHSACH_DONHANG_ADMIN_THATBAI = 'DANHSACH_DONHANG_ADMIN_THATBAI'

export const XOA_DONHANG_REQUEST = 'XOA_DONHANG_REQUEST';
export const XOA_DONHANG_THANHCONG = 'XOA_DONHANG_THANHCONG';
export const XOA_DONHANG_THATBAI = 'XOA_DONHANG_THATBAI';
export const XOA_DONHANG_TAYTRANG = 'XOA_DONHANG_TAYTRANG';

export const GIAO_DONHANG_REQUEST = 'GIAO_DONHANG_REQUEST';
export const GIAO_DONHANG_THANHCONG = 'GIAO_DONHANG_THANHCONG';
export const GIAO_DONHANG_THATBAI = 'GIAO_DONHANG_THATBAI';
export const GIAO_DONHANG_TAYTRANG = 'GIAO_DONHANG_TAYTRANG';

export const THONGKE_DONHANG_REQUEST = 'THONGKE_DONHANG_REQUEST'
export const THONGKE_DONHANG_THANHCONG = 'THONGKE_DONHANG_THANHCONG'
export const THONGKE_DONHANG_THATBAI = 'THONGKE_DONHANG_THATBAI'