export const THEM_HANG_VAO = 'THEM_HANG_VAO'
export const XOA_HANG = 'XOA_HANG'
export const LUU_THONGTIN_GIAOHANG = 'LUU_THONGTIN_GIAOHANG';
export const LUU_PHUONGTHUC_THANHTOAN = 'LUU_PHUONGTHUC_THANHTOAN';
export const GIOHANG_RONG = 'GIOHANG_RONG'