export const KHACHHANG_DANGNHAP_REQUEST = 'KHACHHANG_DANGNHAP_REQUEST';
export const KHACHHANG_DANGNHAP_THANHCONG = 'KHACHHANG_DANGNHAP_THANHCONG';
export const KHACHHANG_DANGNHAP_THATBAI = 'KHACHHANG_DANGNHAP_THATBAI';

export const KHACHHANG_DANGKI_REQUEST = 'KHACHHANG_DANGKI_REQUEST';
export const KHACHHANG_DANGKI_THANHCONG = 'KHACHHANG_DANGKI_THANHCONG';
export const KHACHHANG_DANGKI_THATBAI = 'KHACHHANG_DANGKI_THATBAI';

export const KHACHHANG_THONGTIN_REQUEST = 'KHACHHANG_THONGTIN_REQUEST';
export const KHACHHANG_THONGTIN_THANHCONG = 'KHACHHANG_THONGTIN_THANHCONG';
export const KHACHHANG_THONGTIN_THATBAI = 'KHACHHANG_THONGTIN_THATBAI';

export const KHACHHANG_CAPNHAT_THONGTIN_REQUEST = 'KHACHHANG_CAPNHAT_THONGTIN_REQUEST';
export const KHACHHANG_CAPNHAT_THONGTIN_THANHCONG = 'KHACHHANG_CAPNHAT_THONGTIN_THANHCONG';
export const KHACHHANG_CAPNHAT_THONGTIN_THATBAI = 'KHACHHANG_CAPNHAT_THONGTIN_THATBAI';
export const TAYTRANG_KHACHHANG_CAPNHAT_THONGTIN = 'TAYTRANG_KHACHHANG_CAPNHAT_THONGTIN';

export const DANHSACH_TAIKHOAN_REQUEST = 'DANHSACH_TAIKHOAN_REQUEST';
export const DANHSACH_TAIKHOAN_THANHCONG = 'DANHSACH_TAIKHOAN_THANHCONG';
export const DANHSACH_TAIKHOAN_THATBAI = 'DANHSACH_TAIKHOAN_THATBAI';
export const DANHSACH_TAIKHOAN_TAYTRANG = 'DANHSACH_TAIKHOAN_TAYTRANG';

export const XOA_TAIKHOAN_REQUEST = 'XOA_TAIKHOAN_REQUEST';
export const XOA_TAIKHOAN_THANHCONG = 'XOA_TAIKHOAN_THANHCONG';
export const XOA_TAIKHOAN_THATBAI = 'XOA_TAIKHOAN_THATBAI';
export const XOA_TAIKHOAN_TAYTRANG = 'XOA_TAIKHOAN_TAYTRANG';

export const CAPNHAT_TAIKHOAN_REQUEST = 'CAPNHAT_TAIKHOAN_REQUEST';
export const CAPNHAT_TAIKHOAN_THANHCONG = 'CAPNHAT_TAIKHOAN_THANHCONG';
export const CAPNHAT_TAIKHOAN_THATBAI = 'CAPNHAT_TAIKHOAN_THATBAI';
export const CAPNHAT_TAIKHOAN_TAYTRANG = 'CAPNHAT_TAIKHOAN_TAYTRANG'

export const KHACHHANG_DANGXUAT = 'KHACHHANG_DANGXUAT';

export const DIACHI_KHACHHANG_XACNHAN = 'DIACHI_KHACHHANG_XACNHAN';