export const SANPHAM_DANHSACH_REQUEST = 'SANPHAM_DANHSACH_REQUEST';
export const SANPHAM_DANHSACH_THANHCONG = 'SANPHAM_DANHSACH_THANHCONG';
export const SANPHAM_DANHSACH_THATBAI = 'SANPHAM_DANHSACH_THATBAI';

export const SANPHAM_CHITIET_REQUEST = 'SANPHAM_CHITIET_REQUEST';
export const SANPHAM_CHITIET_THANHCONG = 'SANPHAM_CHITIET_THANHCONG';
export const SANPHAM_CHITIET_THATBAI = 'SANPHAM_CHITIET_THATBAI';

export const TAO_SANPHAM_REQUEST = 'TAO_SANPHAM_REQUEST';
export const TAO_SANPHAM_THANHCONG = 'TAO_SANPHAM_THANHCONG';
export const TAO_SANPHAM_THATBAI = 'TAO_SANPHAM_THATBAI';
export const TAO_SANPHAM_TAYTRANG = 'TAO_SANPHAM_TAYTRANG';

export const CAPNHAT_SANPHAM_REQUEST = 'CAPNHAT_SANPHAM_REQUEST';
export const CAPNHAT_SANPHAM_THANHCONG = 'CAPNHAT_SANPHAM_THANHCONG';
export const CAPNHAT_SANPHAM_THATBAI = 'CAPNHAT_SANPHAM_THATBAI';
export const CAPNHAT_SANPHAM_TAYTRANG = 'CAPNHAT_SANPHAM_TAYTRANG';

export const XOA_SANPHAM_REQUEST = 'XOA_SANPHAM_REQUEST';
export const XOA_SANPHAM_THANHCONG = 'XOA_SANPHAM_THANHCONG';
export const XOA_SANPHAM_THATBAI = 'XOA_SANPHAM_THATBAI';
export const XOA_SANPHAM_TAYTRANG = 'XOA_SANPHAM_TAYTRANG';

export const REVIEW_SANPHAM_REQUEST = 'REVIEW_SANPHAM_REQUEST';
export const REVIEW_SANPHAM_THANHCONG = 'REVIEW_SANPHAM_THANHCONG';
export const REVIEW_SANPHAM_THATBAI = 'REVIEW_SANPHAM_THATBAI';
export const REVIEW_SANPHAM_TAYTRANG = 'REVIEW_SANPHAM_TAYTRANG';

